[build.environment]
  # bypass npm auto install
  NPM_FLAGS="--version"
  NODE_VERSION = "16"

[build]
  base = "./"
  publish = "./dist"
  command = "pnpm run build || ( npm install pnpm && pnpm run build )"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
